import { describe, expect, it } from 'vitest';
import { isCategorisableMessage } from './apply';

/**
 * The guard, which is the one part of the writer that is pure.
 *
 * Worth its own test because it is deliberately *narrower* than
 * `isLinkableMessage`, and the difference is easy to "fix" by somebody who
 * notices the two look almost the same.
 */
describe('isCategorisableMessage', () => {
  it('accepts an inbound reply and nothing else', () => {
    expect(isCategorisableMessage('reply', 'inbound')).toBe(true);
  });

  it('refuses our own reply', () => {
    // A rule matching our words would categorise every ticket where an agent
    // pasted the canned apology, and the report would describe our macros.
    expect(isCategorisableMessage('reply', 'outbound')).toBe(false);
  });

  it('refuses a private note', () => {
    // A note is an agent's opinion. Reading one would launder that opinion into
    // the `source = 'detected'` column the tuning pass trusts to be the
    // machine's own.
    expect(isCategorisableMessage('note', 'inbound')).toBe(false);
    expect(isCategorisableMessage('note', 'outbound')).toBe(false);
  });

  it('refuses system bodies and forwards', () => {
    // `system` text is generated by us ("SLA breached"); a `forward` is by
    // definition somebody else's thread.
    expect(isCategorisableMessage('system', 'inbound')).toBe(false);
    expect(isCategorisableMessage('forward', 'inbound')).toBe(false);
  });
});
