import { and, eq, exists, sql } from 'drizzle-orm';
import { db } from '@/db/client';
import { enqueue } from '@/lib/queue';
import {
  contactShippingAccounts,
  contacts,
  conversationEvents,
  conversationShipments,
  conversationShippingAccounts,
  conversations,
  shipments,
  shippingAccounts,
} from '@/db/schema';
import { detectShipmentRefs, shipmentPatterns } from './detect';
import { normaliseSbid, normaliseTrackingNumber } from './format';

/**
 * Writing the links between conversations, shipments and shipping accounts.
 *
 * Every write here is `onConflictDoNothing` against a natural key, and the audit
 * event is written **only for links that were actually created**. That one
 * condition is the whole idempotency story: a redelivered webhook writes
 * nothing, and a customer who repeats their tracking number in every one of
 * eleven replies gets one link and one timeline entry rather than eleven.
 */

export type LinkSource = 'detected' | 'manual' | 'platform';

export type LinkedFromMessage = {
  trackingNumbers: string[];
  sbids: string[];
};

/**
 * Rows the detector is allowed to look at.
 *
 * `system` bodies are generated by us ("SLA breached", "merged from #123"), and
 * a `forward` is by definition somebody else's thread — linking from one would
 * attribute another conversation's shipments to this one. The filter lives here
 * rather than at the call sites so the live path and the backfill cannot drift
 * into scanning different things.
 */
export function isLinkableMessage(kind: string): boolean {
  return kind === 'reply' || kind === 'note';
}

/**
 * Find every reference in one message and link what it names.
 *
 * Runs on **inbound and outbound** replies and notes. The common sequence is a
 * customer asking where their parcel is, an agent looking it up on the shipping
 * platform, and the number arriving in the reply or in a private note — so
 * scanning only inbound would miss a large share of exactly the tickets worth
 * linking.
 *
 * What it deliberately does not do:
 *
 * - **Never creates a contact.** `resolveContact` owns that, from a channel
 *   identity, and nothing else should.
 * - **Never sets a shipment's shipper or recipient.** A number in a message says
 *   nothing about which end of the parcel the sender is on.
 * - **Never writes `contact_shipping_accounts`.** An SBID in a message proves it
 *   was mentioned in this ticket; it does not prove the sender belongs to that
 *   account, and a recipient quoting the merchant's number is ordinary. The
 *   conversation-level link carries the mention instead.
 * - **Never deletes.** Only a person removes a link.
 */
export async function linkShipmentsFromMessage(input: {
  conversationId: string;
  messageId: string;
  bodyText: string;
  kind: string;
}): Promise<LinkedFromMessage> {
  const empty: LinkedFromMessage = { trackingNumbers: [], sbids: [] };
  if (!isLinkableMessage(input.kind) || !input.bodyText.trim()) return empty;

  const found = detectShipmentRefs(input.bodyText, shipmentPatterns());
  if (found.trackingNumbers.length === 0 && found.sbids.length === 0) return empty;

  const linkedTracking: string[] = [];
  const linkedSbids: string[] = [];

  for (const trackingNumber of found.trackingNumbers) {
    const shipmentId = await upsertShipmentStub(trackingNumber);
    const created = await attachShipment({
      conversationId: input.conversationId,
      shipmentId,
      linkSource: 'detected',
      detectedInMessageId: input.messageId,
    });
    if (created) linkedTracking.push(trackingNumber);
  }

  for (const sbid of found.sbids) {
    const shippingAccountId = await upsertShippingAccountStub(sbid);
    const created = await attachShippingAccount({
      conversationId: input.conversationId,
      shippingAccountId,
      linkSource: 'detected',
      detectedInMessageId: input.messageId,
    });
    if (created) linkedSbids.push(sbid);
  }

  if (linkedTracking.length === 0 && linkedSbids.length === 0) return empty;

  await db.insert(conversationEvents).values({
    conversationId: input.conversationId,
    type: 'shipments_detected',
    actorLabel: 'shipment-detector',
    data: {
      messageId: input.messageId,
      trackingNumbers: linkedTracking,
      sbids: linkedSbids,
    },
  });

  // Touch the conversation so the existing notify_change trigger fires. Without
  // this the new sidebar entry waits for the *next* refresh: the message's own
  // NOTIFY went out at commit time, before any of this existed.
  await db
    .update(conversations)
    .set({ updatedAt: new Date() })
    .where(eq(conversations.id, input.conversationId));

  return { trackingNumbers: linkedTracking, sbids: linkedSbids };
}

/**
 * The shipment row for a tracking number, creating a stub if there is none.
 *
 * Race-safe the same way `resolveContact` is: the unique index is the real
 * guard, and two webhooks arriving together collapse onto one row rather than
 * producing two shipments for one parcel.
 *
 * **A row that was just created asks the platform about itself.** The enqueue
 * lives here rather than at the two call sites so it cannot be forgotten by the
 * third: every path that first learns of a parcel — the detector, an agent
 * typing a number, whatever comes next — leaves exactly one `sync_shipment`
 * behind it. Only on creation, so a customer repeating their number in eleven
 * replies still costs one lookup rather than eleven, and the console's refresh
 * button stays the way to ask again on purpose.
 *
 * No `dedupeKey`, for the reason `worker/handlers/sync-shipment.ts` sets out at
 * length: the index behind it is unique over the whole table, so a key spent on
 * this parcel today would silently swallow every future sync of it.
 *
 * A queue that cannot be written to must not stop the link being made. The
 * ticket is the thing the customer is waiting on; a status that arrives late,
 * or on the sweep instead, costs nobody anything.
 */
export async function upsertShipmentStub(trackingNumber: string): Promise<string> {
  const canonical = normaliseTrackingNumber(trackingNumber);
  if (!canonical) throw new Error('Cannot create a shipment without a tracking number');

  const inserted = await db
    .insert(shipments)
    .values({ trackingNumber: canonical })
    .onConflictDoNothing({ target: shipments.trackingNumber })
    .returning({ id: shipments.id });

  if (inserted[0]) {
    const shipmentId = inserted[0].id;
    try {
      await enqueue('sync_shipment', { shipmentId });
    } catch (error) {
      console.error(`[shipments] could not queue a sync for ${canonical}`, error);
    }
    return shipmentId;
  }

  const existing = await db
    .select({ id: shipments.id })
    .from(shipments)
    .where(eq(shipments.trackingNumber, canonical))
    .limit(1);

  if (!existing[0]) throw new Error(`Shipment ${canonical} could not be resolved after a conflict`);
  return existing[0].id;
}

export async function upsertShippingAccountStub(sbid: string): Promise<string> {
  const canonical = normaliseSbid(sbid);
  if (!canonical) throw new Error('Cannot create a shipping account without an SBID');

  const inserted = await db
    .insert(shippingAccounts)
    .values({ sbid: canonical })
    .onConflictDoNothing({ target: shippingAccounts.sbid })
    .returning({ id: shippingAccounts.id });

  if (inserted[0]) return inserted[0].id;

  const existing = await db
    .select({ id: shippingAccounts.id })
    .from(shippingAccounts)
    .where(eq(shippingAccounts.sbid, canonical))
    .limit(1);

  if (!existing[0]) throw new Error(`Shipping account ${canonical} could not be resolved`);
  return existing[0].id;
}

/** True when the link did not already exist. */
export async function attachShipment(input: {
  conversationId: string;
  shipmentId: string;
  linkSource: LinkSource;
  detectedInMessageId?: string | null;
  linkedByAgentId?: string | null;
}): Promise<boolean> {
  const rows = await db
    .insert(conversationShipments)
    .values({
      conversationId: input.conversationId,
      shipmentId: input.shipmentId,
      linkSource: input.linkSource,
      detectedInMessageId: input.detectedInMessageId ?? null,
      linkedByAgentId: input.linkedByAgentId ?? null,
    })
    .onConflictDoNothing({
      target: [conversationShipments.conversationId, conversationShipments.shipmentId],
    })
    .returning({ shipmentId: conversationShipments.shipmentId });

  return rows.length > 0;
}

export async function attachShippingAccount(input: {
  conversationId: string;
  shippingAccountId: string;
  linkSource: LinkSource;
  detectedInMessageId?: string | null;
  linkedByAgentId?: string | null;
}): Promise<boolean> {
  const rows = await db
    .insert(conversationShippingAccounts)
    .values({
      conversationId: input.conversationId,
      shippingAccountId: input.shippingAccountId,
      linkSource: input.linkSource,
      detectedInMessageId: input.detectedInMessageId ?? null,
      linkedByAgentId: input.linkedByAgentId ?? null,
    })
    .onConflictDoNothing({
      target: [
        conversationShippingAccounts.conversationId,
        conversationShippingAccounts.shippingAccountId,
      ],
    })
    .returning({ shippingAccountId: conversationShippingAccounts.shippingAccountId });

  return rows.length > 0;
}

export async function detachShipment(conversationId: string, shipmentId: string): Promise<void> {
  await db
    .delete(conversationShipments)
    .where(
      and(
        eq(conversationShipments.conversationId, conversationId),
        eq(conversationShipments.shipmentId, shipmentId),
      ),
    );
}

export async function detachShippingAccount(
  conversationId: string,
  shippingAccountId: string,
): Promise<void> {
  await db
    .delete(conversationShippingAccounts)
    .where(
      and(
        eq(conversationShippingAccounts.conversationId, conversationId),
        eq(conversationShippingAccounts.shippingAccountId, shippingAccountId),
      ),
    );
}

/**
 * Says that a person can speak for a shipping account.
 *
 * Only ever called from an agent's action or a platform sync — never from
 * detected text, for the reason in `linkShipmentsFromMessage`.
 */
export async function addContactToShippingAccount(input: {
  contactId: string;
  shippingAccountId: string;
  linkSource: LinkSource;
  linkedByAgentId?: string | null;
}): Promise<boolean> {
  const rows = await db
    .insert(contactShippingAccounts)
    .values({
      contactId: input.contactId,
      shippingAccountId: input.shippingAccountId,
      linkSource: input.linkSource,
      linkedByAgentId: input.linkedByAgentId ?? null,
    })
    .onConflictDoNothing({
      target: [contactShippingAccounts.contactId, contactShippingAccounts.shippingAccountId],
    })
    .returning({ contactId: contactShippingAccounts.contactId });

  await refreshContactRoles(input.contactId);
  return rows.length > 0;
}

export async function removeContactFromShippingAccount(
  contactId: string,
  shippingAccountId: string,
): Promise<void> {
  await db
    .delete(contactShippingAccounts)
    .where(
      and(
        eq(contactShippingAccounts.contactId, contactId),
        eq(contactShippingAccounts.shippingAccountId, shippingAccountId),
      ),
    );

  await refreshContactRoles(contactId);
}

/**
 * Brings `contacts.is_shipper` / `is_recipient` up to date from the
 * relationship rows.
 *
 * Deliberately **additive**: it turns a flag on when it can prove it and never
 * off. The flags are also settable by an agent, and a person who designated a
 * contact as a shipper before that contact holds any account must not have it
 * silently undone by the next sync. The relationship rows remain the truth; this
 * is a cache so a customer list can badge and filter without two correlated
 * EXISTS subqueries per row.
 */
export async function refreshContactRoles(contactId: string): Promise<void> {
  const holdsAccount = exists(
    db
      .select({ one: sql`1` })
      .from(contactShippingAccounts)
      .where(eq(contactShippingAccounts.contactId, contactId)),
  );

  const namedAsShipper = exists(
    db
      .select({ one: sql`1` })
      .from(shipments)
      .where(eq(shipments.shipperContactId, contactId)),
  );

  const namedAsRecipient = exists(
    db
      .select({ one: sql`1` })
      .from(shipments)
      .where(eq(shipments.recipientContactId, contactId)),
  );

  await db
    .update(contacts)
    .set({
      isShipper: sql`${contacts.isShipper} OR ${holdsAccount} OR ${namedAsShipper}`,
      isRecipient: sql`${contacts.isRecipient} OR ${namedAsRecipient}`,
    })
    .where(eq(contacts.id, contactId));
}
