-- Post-migration SQL: moving a single-language body onto the bilingual pair
-- that replaced it.
--
-- Migration 0025 added `canned_responses.body_{html,text}_{ar,en}` and
-- `holidays.name_{ar,en}` as `text NOT NULL DEFAULT ''`, which is the only shape
-- an ADD COLUMN on a live table can take — and it means every row that existed
-- before the migration reads as having no body and no name at all. Nothing else
-- copies the old columns across, and the new read paths only look at the new
-- ones, so without this the release is silent data loss of the worst kind:
--
--   * `availableLocales` answers `[]` for every existing canned response. The
--     composer's picker still lists them, inserts nothing when one is chosen,
--     and says nothing about why; `sendCannedReply` logs "references a canned
--     response with no body" and returns, so every automation rule that replies
--     stops replying with no error anywhere a person looks.
--   * `holidayName` answers null for every existing holiday, so `{{holiday}}`
--     collapses and the out-of-hours message that exists to name the day does
--     not name it.
--
-- Here rather than in the generated migration because `db/migrations/**` is
-- generated from `db/schema/` and regenerated by CI, and because this file is
-- replayed after every deploy — which is the property that makes it safe to add
-- after the migration has already run somewhere.
--
-- **Which language.** The old column held one body in whichever language it was
-- written in, and nothing recorded which. So it is read off the script, by the
-- same rule `preferredLocale` in `lib/tickets/locale.ts` applies to a customer's
-- message: more Arabic letters than Latin ones means Arabic. Counting rather
-- than looking for the first Arabic character is what keeps a tracking number
-- inside an Arabic body Arabic, and a delivery district inside an English one
-- English. The ranges are the same five that function uses, written as literal
-- endpoints — Arabic, Arabic Supplement, Arabic Extended-A, and the two
-- presentation-form blocks.
--
-- **Idempotent**, on the same condition that makes it correct: a row is touched
-- only while both new columns are still blank, so the second run selects
-- nothing. A row somebody has since edited in the console is never overwritten,
-- and neither is one where an admin deliberately cleared a language.

-- --------------------------------------------------------------------------
-- Canned responses
--
-- Both forms move together. `body_html` can legitimately be blank where
-- `body_text` is not — a row written by hand, or by a backfill — and that is
-- left as it is rather than derived here: `sendCannedReply` already falls back
-- to `textToHtml(bodyText)` for exactly that case, and generating markup in SQL
-- would be a second implementation of a function this codebase already has.
-- --------------------------------------------------------------------------
UPDATE canned_responses c
   SET body_text_ar = CASE WHEN s.arabic THEN c.body_text ELSE c.body_text_ar END,
       body_html_ar = CASE WHEN s.arabic THEN c.body_html ELSE c.body_html_ar END,
       body_text_en = CASE WHEN s.arabic THEN c.body_text_en ELSE c.body_text END,
       body_html_en = CASE WHEN s.arabic THEN c.body_html_en ELSE c.body_html END
  FROM (
    SELECT id,
           length(regexp_replace(body_text, '[^؀-ۿݐ-ݿࢠ-ࣿﭐ-﷿ﹰ-﻿]', '', 'g'))
             > length(regexp_replace(body_text, '[^A-Za-z]', '', 'g')) AS arabic
      FROM canned_responses
     WHERE btrim(body_text) <> ''
       AND btrim(body_text_ar) = ''
       AND btrim(body_text_en) = ''
  ) s
 WHERE c.id = s.id;

-- --------------------------------------------------------------------------
-- Holiday names
--
-- Shorter text and therefore a weaker signal, but the failure it is guarding
-- against is one-sided: a name filed under the wrong language still renders,
-- because `holidayName` falls back to whichever side was filled in. A name filed
-- under neither renders as nothing at all.
-- --------------------------------------------------------------------------
UPDATE holidays h
   SET name_ar = CASE WHEN s.arabic THEN h.name ELSE h.name_ar END,
       name_en = CASE WHEN s.arabic THEN h.name_en ELSE h.name END
  FROM (
    SELECT id,
           length(regexp_replace(name, '[^؀-ۿݐ-ݿࢠ-ࣿﭐ-﷿ﹰ-﻿]', '', 'g'))
             > length(regexp_replace(name, '[^A-Za-z]', '', 'g')) AS arabic
      FROM holidays
     WHERE btrim(name) <> ''
       AND btrim(name_ar) = ''
       AND btrim(name_en) = ''
  ) s
 WHERE h.id = s.id;
